
policy_path: "/home/quad/github/Gym to Mujoco/policies/policy_1.pt"
xml_path: "/home/quad/github/Gym to Mujoco/resources/robots/trakr/quadruped.xml"

# Total simulation time
simulation_duration: 60.0

# Simulation time step
simulation_dt: 0.002

# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
kds: [0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]

default_angles: [0, 0, 0.0, 0, 0, 0.0, 
                 0, 0, 0.0, 0, 0, 0.0]

ang_vel_scale: 0.25
lin_vel_scale: 2
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [1,1,1 ]
num_actions: 12
num_obs: 48

cmd_init: [0, 0.5 , 0]